{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "97bf4357-b6a4-4df3-adad-5fe5f95c385e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Arquivos encontrados na pasta: ['Landsat_Metadata_1984.csv', 'Landsat_Metadata_1988.csv', 'Landsat_Metadata_1992.csv', 'Landsat_Metadata_1996.csv', 'Landsat_Metadata_2000.csv', 'Landsat_Metadata_2004.csv', 'Landsat_Metadata_2008.csv', 'Landsat_Metadata_2012.csv', 'Landsat_Metadata_2016.csv', 'Landsat_Metadata_2020.csv', 'Landsat_Metadata_2024.csv']\n",
      "\n",
      "Processando o arquivo: Landsat_Metadata_1984.csv\n",
      "\n",
      "Processando o arquivo: Landsat_Metadata_1988.csv\n",
      "\n",
      "Processando o arquivo: Landsat_Metadata_1992.csv\n",
      "\n",
      "Processando o arquivo: Landsat_Metadata_1996.csv\n",
      "\n",
      "Processando o arquivo: Landsat_Metadata_2000.csv\n",
      "\n",
      "Processando o arquivo: Landsat_Metadata_2004.csv\n",
      "\n",
      "Processando o arquivo: Landsat_Metadata_2008.csv\n",
      "\n",
      "Processando o arquivo: Landsat_Metadata_2012.csv\n",
      "\n",
      "Processando o arquivo: Landsat_Metadata_2016.csv\n",
      "\n",
      "Processando o arquivo: Landsat_Metadata_2020.csv\n",
      "\n",
      "Processando o arquivo: Landsat_Metadata_2024.csv\n",
      "\n",
      "Tabela final com os resultados:\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Ano</th>\n",
       "      <th>Média do RMSE (m)</th>\n",
       "      <th>Erro de Pixel (Ep) (m)</th>\n",
       "      <th>Incerteza Total (U) (m)</th>\n",
       "      <th>Erro Residual Médio (m)</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1984</td>\n",
       "      <td>8.581</td>\n",
       "      <td>30</td>\n",
       "      <td>31.203</td>\n",
       "      <td>2.054</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1988</td>\n",
       "      <td>8.151</td>\n",
       "      <td>30</td>\n",
       "      <td>31.087</td>\n",
       "      <td>2.036</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>1992</td>\n",
       "      <td>8.072</td>\n",
       "      <td>30</td>\n",
       "      <td>31.067</td>\n",
       "      <td>1.899</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1996</td>\n",
       "      <td>6.959</td>\n",
       "      <td>30</td>\n",
       "      <td>30.796</td>\n",
       "      <td>1.834</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2000</td>\n",
       "      <td>6.796</td>\n",
       "      <td>30</td>\n",
       "      <td>30.760</td>\n",
       "      <td>1.774</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>2004</td>\n",
       "      <td>6.426</td>\n",
       "      <td>30</td>\n",
       "      <td>30.681</td>\n",
       "      <td>1.693</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>2008</td>\n",
       "      <td>6.075</td>\n",
       "      <td>30</td>\n",
       "      <td>30.609</td>\n",
       "      <td>1.689</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>2012</td>\n",
       "      <td>5.331</td>\n",
       "      <td>30</td>\n",
       "      <td>30.470</td>\n",
       "      <td>1.371</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>2016</td>\n",
       "      <td>8.311</td>\n",
       "      <td>30</td>\n",
       "      <td>31.130</td>\n",
       "      <td>1.055</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>2020</td>\n",
       "      <td>8.560</td>\n",
       "      <td>30</td>\n",
       "      <td>31.197</td>\n",
       "      <td>0.808</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>2024</td>\n",
       "      <td>8.594</td>\n",
       "      <td>30</td>\n",
       "      <td>31.207</td>\n",
       "      <td>0.842</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "     Ano  Média do RMSE (m)  Erro de Pixel (Ep) (m)  Incerteza Total (U) (m)  \\\n",
       "0   1984              8.581                      30                   31.203   \n",
       "1   1988              8.151                      30                   31.087   \n",
       "2   1992              8.072                      30                   31.067   \n",
       "3   1996              6.959                      30                   30.796   \n",
       "4   2000              6.796                      30                   30.760   \n",
       "5   2004              6.426                      30                   30.681   \n",
       "6   2008              6.075                      30                   30.609   \n",
       "7   2012              5.331                      30                   30.470   \n",
       "8   2016              8.311                      30                   31.130   \n",
       "9   2020              8.560                      30                   31.197   \n",
       "10  2024              8.594                      30                   31.207   \n",
       "\n",
       "    Erro Residual Médio (m)  \n",
       "0                     2.054  \n",
       "1                     2.036  \n",
       "2                     1.899  \n",
       "3                     1.834  \n",
       "4                     1.774  \n",
       "5                     1.693  \n",
       "6                     1.689  \n",
       "7                     1.371  \n",
       "8                     1.055  \n",
       "9                     0.808  \n",
       "10                    0.842  "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "import os\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from IPython.display import display\n",
    "\n",
    "# Caminho fixo da pasta onde os arquivos CSV estão localizados\n",
    "pasta_arquivos = r\"D:\\DOUTORADO\\ARTIGOS\\04_LC\\METADADOS DAS IMGENS\"\n",
    "\n",
    "# Verificar se os arquivos estão na pasta\n",
    "arquivos_na_pasta = os.listdir(pasta_arquivos)\n",
    "print(f\"Arquivos encontrados na pasta: {arquivos_na_pasta}\")\n",
    "\n",
    "# Lista dos nomes dos arquivos CSV\n",
    "arquivos = [\n",
    "    \"Landsat_Metadata_1984.csv\",\n",
    "    \"Landsat_Metadata_1988.csv\",\n",
    "    \"Landsat_Metadata_1992.csv\",\n",
    "    \"Landsat_Metadata_1996.csv\",\n",
    "    \"Landsat_Metadata_2000.csv\",\n",
    "    \"Landsat_Metadata_2004.csv\",\n",
    "    \"Landsat_Metadata_2008.csv\",\n",
    "    \"Landsat_Metadata_2012.csv\",\n",
    "    \"Landsat_Metadata_2016.csv\",\n",
    "    \"Landsat_Metadata_2020.csv\",\n",
    "    \"Landsat_Metadata_2024.csv\"\n",
    "]\n",
    "\n",
    "# Erro de pixel fixo (30 metros)\n",
    "Ep = 30\n",
    "\n",
    "# Lista para armazenar os resultados de cada arquivo\n",
    "resultados = []\n",
    "\n",
    "# Iterar sobre os arquivos e calcular a média do RMSE, a incerteza total e o erro residual\n",
    "for arquivo in arquivos:\n",
    "    caminho_arquivo = os.path.join(pasta_arquivos, arquivo)\n",
    "    \n",
    "    if os.path.exists(caminho_arquivo):\n",
    "        try:\n",
    "            print(f\"\\nProcessando o arquivo: {arquivo}\")\n",
    "            df = pd.read_csv(caminho_arquivo)\n",
    "\n",
    "            coluna_eg = 'GEOMETRIC_RMSE_MODEL'\n",
    "\n",
    "            if coluna_eg in df.columns:\n",
    "                media_rmse = df[coluna_eg].mean()\n",
    "                incerteza_total = np.sqrt(media_rmse**2 + Ep**2)\n",
    "\n",
    "                # Cálculo dos erros residuais (diferença entre cada RMSE e a média)\n",
    "                df['Erro Residual'] = df[coluna_eg] - media_rmse\n",
    "\n",
    "                # RMSE dos RMSEs: medida da variabilidade dos erros\n",
    "                erro_residual_medio = np.sqrt(np.mean(df['Erro Residual']**2))\n",
    "\n",
    "                resultados.append({\n",
    "                    'Ano': arquivo.split('_')[2].split('.')[0],\n",
    "                    'Média do RMSE (m)': round(media_rmse, 3),\n",
    "                    'Erro de Pixel (Ep) (m)': Ep,\n",
    "                    'Incerteza Total (U) (m)': round(incerteza_total, 3),\n",
    "                    'Erro Residual Médio (m)': round(erro_residual_medio, 3)\n",
    "                })\n",
    "            else:\n",
    "                print(f\"Coluna '{coluna_eg}' não encontrada no arquivo {arquivo}.\")\n",
    "        except Exception as e:\n",
    "            print(f\"Erro ao processar o arquivo {arquivo}: {e}\")\n",
    "    else:\n",
    "        print(f\"Arquivo {arquivo} não encontrado no caminho {caminho_arquivo}.\")\n",
    "\n",
    "# Criar um DataFrame com todos os resultados\n",
    "if resultados:\n",
    "    resultados_df = pd.DataFrame(resultados)\n",
    "    print(\"\\nTabela final com os resultados:\")\n",
    "    display(resultados_df)\n",
    "else:\n",
    "    print(\"Nenhum resultado foi gerado.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e5016345-e2f5-48e3-968a-231daa2bb2e1",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}