{
 "cells": [
  {
   "cell_type": {
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 30,
   "id": "0765781f-ec26-4eeb-9ef5-23259deb2c8e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Incerteza da taxa calculada (U_taxa): 1.1033 m/ano\n",
      "\n",
      "✔️ Tabela de significância por setor salva em: C:\\Users\\rafam\\Documents\\DSAS_ZC_ATLANTICO\\significancia_por_setor_2024.xlsx\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "# Dados de incerteza por ano\n",
    "dados_incerteza = {\n",
    "    'Ano': [1984, 1988, 1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020, 2024],\n",
    "    'U (m)': [31.20313, 31.087496, 31.066874, 30.796462, 30.76017, 30.680610, \n",
    "              30.608914, 30.469932, 31.129918, 31.197335, 31.206661]\n",
    "}\n",
    "df_incerteza = pd.DataFrame(dados_incerteza)\n",
    "\n",
    "# Carregar dados DSAS\n",
    "caminho_arquivo = r'C:\\Users\\rafam\\Documents\\DSAS_ZC_ATLANTICO\\DSAS_GERAL.xlsx'\n",
    "df_dsas = pd.read_excel(caminho_arquivo, sheet_name='dsas')\n",
    "\n",
    "# Definir anos de início e fim\n",
    "ano_inicial = 1984\n",
    "ano_final = 2024\n",
    "U1 = df_incerteza[df_incerteza['Ano'] == ano_inicial]['U (m)'].values[0]\n",
    "U2 = df_incerteza[df_incerteza['Ano'] == ano_final]['U (m)'].values[0]\n",
    "delta_t = ano_final - ano_inicial\n",
    "\n",
    "# Cálculo atualizado de incerteza da taxa\n",
    "U_taxa = np.sqrt(U1**2 + U2**2) / delta_t\n",
    "print(f\"Incerteza da taxa calculada (U_taxa): {U_taxa:.4f} m/ano\")\n",
    "\n",
    "# Classificação com base na nova U_taxa\n",
    "def classificar_epr(epr):\n",
    "    if abs(epr) > U_taxa:\n",
    "        return 'Erosão Significativa' if epr < 0 else 'Progradação Significativa'\n",
    "    else:\n",
    "        return 'Não Significativa'\n",
    "\n",
    "# Adiciona a coluna de significância\n",
    "df_dsas['Significância'] = df_dsas['EPR'].apply(classificar_epr)\n",
    "\n",
    "# Dividir por setor\n",
    "setores = {\n",
    "    'I': 'Salinópolis', 'II': 'São João de Pirabas', 'III': 'Quatipuru',\n",
    "    'IV': 'Tracuateua', 'V': 'Bragança', 'VI': 'Augusto Corrêa', 'VII': 'Viseu'\n",
    "}\n",
    "\n",
    "# Tabela de significância por setor\n",
    "resultados_por_setor = []\n",
    "\n",
    "for setor, nome in setores.items():\n",
    "    subset = df_dsas[df_dsas['Setor'] == setor]\n",
    "    \n",
    "    # Contagem por tipo de significância\n",
    "    contagem = subset['Significância'].value_counts()\n",
    "    total_setor = len(subset)\n",
    "    percentuais = (contagem / total_setor * 100).round(2)\n",
    "    \n",
    "    # Adiciona os resultados à lista\n",
    "    resultados_por_setor.append({\n",
    "        'Setor': nome,\n",
    "        'Não Significativa (n)': contagem.get('Não Significativa', 0),\n",
    "        'Não Significativa (%)': percentuais.get('Não Significativa', 0.00),\n",
    "        'Erosão Significativa (n)': contagem.get('Erosão Significativa', 0),\n",
    "        'Erosão Significativa (%)': percentuais.get('Erosão Significativa', 0.00),\n",
    "        'Progradação Significativa (n)': contagem.get('Progradação Significativa', 0),\n",
    "        'Progradação Significativa (%)': percentuais.get('Progradação Significativa', 0.00)\n",
    "    })\n",
    "\n",
    "# Criar DataFrame de resultados por setor\n",
    "df_resultados_setor = pd.DataFrame(resultados_por_setor)\n",
    "\n",
    "# Exportar para Excel\n",
    "caminho_saida_setor = r'C:\\Users\\rafam\\Documents\\DSAS_ZC_ATLANTICO\\significancia_por_setor_2024.xlsx'\n",
    "df_resultados_setor.to_excel(caminho_saida_setor, index=False)\n",
    "\n",
    "print(f\"\\n✔️ Tabela de significância por setor salva em: {caminho_saida_setor}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 58,
   "id": "0cf665cf-6bb4-454f-adfc-770188bb81b8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "📊 Tabela de Incerteza por Setor - EPR\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Significância_EPR</th>\n",
       "      <th>Erosão Significativa</th>\n",
       "      <th>Não Significativa</th>\n",
       "      <th>Progradação Significativa</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Tipo</th>\n",
       "      <th>Setor</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th rowspan=\"7\" valign=\"top\">Contagem</th>\n",
       "      <th>I</th>\n",
       "      <td>117.00</td>\n",
       "      <td>85.00</td>\n",
       "      <td>162.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>II</th>\n",
       "      <td>257.00</td>\n",
       "      <td>62.00</td>\n",
       "      <td>334.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>III</th>\n",
       "      <td>137.00</td>\n",
       "      <td>25.00</td>\n",
       "      <td>236.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>IV</th>\n",
       "      <td>78.00</td>\n",
       "      <td>32.00</td>\n",
       "      <td>332.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>V</th>\n",
       "      <td>181.00</td>\n",
       "      <td>38.00</td>\n",
       "      <td>367.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>VI</th>\n",
       "      <td>368.00</td>\n",
       "      <td>100.00</td>\n",
       "      <td>583.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>VII</th>\n",
       "      <td>356.00</td>\n",
       "      <td>42.00</td>\n",
       "      <td>494.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th rowspan=\"7\" valign=\"top\">Percentual</th>\n",
       "      <th>I</th>\n",
       "      <td>32.14</td>\n",
       "      <td>23.35</td>\n",
       "      <td>44.51</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>II</th>\n",
       "      <td>39.36</td>\n",
       "      <td>9.49</td>\n",
       "      <td>51.15</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>III</th>\n",
       "      <td>34.42</td>\n",
       "      <td>6.28</td>\n",
       "      <td>59.30</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>IV</th>\n",
       "      <td>17.65</td>\n",
       "      <td>7.24</td>\n",
       "      <td>75.11</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>V</th>\n",
       "      <td>30.89</td>\n",
       "      <td>6.48</td>\n",
       "      <td>62.63</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>VI</th>\n",
       "      <td>35.01</td>\n",
       "      <td>9.51</td>\n",
       "      <td>55.47</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>VII</th>\n",
       "      <td>39.91</td>\n",
       "      <td>4.71</td>\n",
       "      <td>55.38</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "Significância_EPR  Erosão Significativa  Não Significativa  \\\n",
       "Tipo       Setor                                             \n",
       "Contagem   I                     117.00              85.00   \n",
       "           II                    257.00              62.00   \n",
       "           III                   137.00              25.00   \n",
       "           IV                     78.00              32.00   \n",
       "           V                     181.00              38.00   \n",
       "           VI                    368.00             100.00   \n",
       "           VII                   356.00              42.00   \n",
       "Percentual I                      32.14              23.35   \n",
       "           II                     39.36               9.49   \n",
       "           III                    34.42               6.28   \n",
       "           IV                     17.65               7.24   \n",
       "           V                      30.89               6.48   \n",
       "           VI                     35.01               9.51   \n",
       "           VII                    39.91               4.71   \n",
       "\n",
       "Significância_EPR  Progradação Significativa  \n",
       "Tipo       Setor                              \n",
       "Contagem   I                          162.00  \n",
       "           II                         334.00  \n",
       "           III                        236.00  \n",
       "           IV                         332.00  \n",
       "           V                          367.00  \n",
       "           VI                         583.00  \n",
       "           VII                        494.00  \n",
       "Percentual I                           44.51  \n",
       "           II                          51.15  \n",
       "           III                         59.30  \n",
       "           IV                          75.11  \n",
       "           V                           62.63  \n",
       "           VI                          55.47  \n",
       "           VII                         55.38  "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "📊 Tabela de Incerteza por Setor - LRR\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Significância_LRR</th>\n",
       "      <th>Erosão Significativa</th>\n",
       "      <th>Não Significativa</th>\n",
       "      <th>Progradação Significativa</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Tipo</th>\n",
       "      <th>Setor</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th rowspan=\"7\" valign=\"top\">Contagem</th>\n",
       "      <th>I</th>\n",
       "      <td>62.00</td>\n",
       "      <td>211.00</td>\n",
       "      <td>91.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>II</th>\n",
       "      <td>142.00</td>\n",
       "      <td>272.00</td>\n",
       "      <td>239.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>III</th>\n",
       "      <td>85.00</td>\n",
       "      <td>112.00</td>\n",
       "      <td>201.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>IV</th>\n",
       "      <td>68.00</td>\n",
       "      <td>91.00</td>\n",
       "      <td>283.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>V</th>\n",
       "      <td>142.00</td>\n",
       "      <td>136.00</td>\n",
       "      <td>308.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>VI</th>\n",
       "      <td>249.00</td>\n",
       "      <td>315.00</td>\n",
       "      <td>487.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>VII</th>\n",
       "      <td>261.00</td>\n",
       "      <td>207.00</td>\n",
       "      <td>424.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th rowspan=\"7\" valign=\"top\">Percentual</th>\n",
       "      <th>I</th>\n",
       "      <td>17.03</td>\n",
       "      <td>57.97</td>\n",
       "      <td>25.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>II</th>\n",
       "      <td>21.75</td>\n",
       "      <td>41.65</td>\n",
       "      <td>36.60</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>III</th>\n",
       "      <td>21.36</td>\n",
       "      <td>28.14</td>\n",
       "      <td>50.50</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>IV</th>\n",
       "      <td>15.38</td>\n",
       "      <td>20.59</td>\n",
       "      <td>64.03</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>V</th>\n",
       "      <td>24.23</td>\n",
       "      <td>23.21</td>\n",
       "      <td>52.56</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>VI</th>\n",
       "      <td>23.69</td>\n",
       "      <td>29.97</td>\n",
       "      <td>46.34</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>VII</th>\n",
       "      <td>29.26</td>\n",
       "      <td>23.21</td>\n",
       "      <td>47.53</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "Significância_LRR  Erosão Significativa  Não Significativa  \\\n",
       "Tipo       Setor                                             \n",
       "Contagem   I                      62.00             211.00   \n",
       "           II                    142.00             272.00   \n",
       "           III                    85.00             112.00   \n",
       "           IV                     68.00              91.00   \n",
       "           V                     142.00             136.00   \n",
       "           VI                    249.00             315.00   \n",
       "           VII                   261.00             207.00   \n",
       "Percentual I                      17.03              57.97   \n",
       "           II                     21.75              41.65   \n",
       "           III                    21.36              28.14   \n",
       "           IV                     15.38              20.59   \n",
       "           V                      24.23              23.21   \n",
       "           VI                     23.69              29.97   \n",
       "           VII                    29.26              23.21   \n",
       "\n",
       "Significância_LRR  Progradação Significativa  \n",
       "Tipo       Setor                              \n",
       "Contagem   I                           91.00  \n",
       "           II                         239.00  \n",
       "           III                        201.00  \n",
       "           IV                         283.00  \n",
       "           V                          308.00  \n",
       "           VI                         487.00  \n",
       "           VII                        424.00  \n",
       "Percentual I                           25.00  \n",
       "           II                          36.60  \n",
       "           III                         50.50  \n",
       "           IV                          64.03  \n",
       "           V                           52.56  \n",
       "           VI                          46.34  \n",
       "           VII                         47.53  "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "✔️ Arquivos salvos em:\n",
      "C:\\Users\\rafam\\Documents\\DSAS_ZC_ATLANTICO\\INCERTEZAS_EPR.xlsx\n",
      "C:\\Users\\rafam\\Documents\\DSAS_ZC_ATLANTICO\\INCERTEZAS_LRR.xlsx\n",
      "\n",
      "📊 Tabela Geral - EPR\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Significância</th>\n",
       "      <th>Contagem</th>\n",
       "      <th>Percentual (%)</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Progradação Significativa</td>\n",
       "      <td>2508</td>\n",
       "      <td>57.18</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Erosão Significativa</td>\n",
       "      <td>1494</td>\n",
       "      <td>34.06</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Não Significativa</td>\n",
       "      <td>384</td>\n",
       "      <td>8.76</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "               Significância  Contagem  Percentual (%)\n",
       "0  Progradação Significativa      2508           57.18\n",
       "1       Erosão Significativa      1494           34.06\n",
       "2          Não Significativa       384            8.76"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✔️ Tabela geral de EPR salva em: C:\\Users\\rafam\\Documents\\DSAS_ZC_ATLANTICO\\INCERTEZAS_GERAL_EPR.xlsx\n",
      "\n",
      "📊 Tabela Geral - LRR\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Significância</th>\n",
       "      <th>Contagem</th>\n",
       "      <th>Percentual (%)</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Progradação Significativa</td>\n",
       "      <td>2033</td>\n",
       "      <td>46.35</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Não Significativa</td>\n",
       "      <td>1344</td>\n",
       "      <td>30.64</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Erosão Significativa</td>\n",
       "      <td>1009</td>\n",
       "      <td>23.01</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "               Significância  Contagem  Percentual (%)\n",
       "0  Progradação Significativa      2033           46.35\n",
       "1          Não Significativa      1344           30.64\n",
       "2       Erosão Significativa      1009           23.01"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✔️ Tabela geral de LRR salva em: C:\\Users\\rafam\\Documents\\DSAS_ZC_ATLANTICO\\INCERTEZAS_GERAL_LRR.xlsx\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "# Carregar dados da planilha\n",
    "caminho_arquivo = r'C:\\Users\\rafam\\Documents\\DSAS_ZC_ATLANTICO\\DSAS_GERAL.xlsx'\n",
    "df = pd.read_excel(caminho_arquivo, sheet_name='dsas')\n",
    "\n",
    "# Classificação baseada em LRR e LCI90\n",
    "def classificar_lrr(row):\n",
    "    if abs(row['LRR']) > row['LCI90']:\n",
    "        return 'Erosão Significativa' if row['LRR'] < 0 else 'Progradação Significativa'\n",
    "    else:\n",
    "        return 'Não Significativa'\n",
    "\n",
    "df['Significância_LRR'] = df.apply(classificar_lrr, axis=1)\n",
    "\n",
    "# Classificação baseada em EPR e incerteza (pré-calculada)\n",
    "def classificar_epr(row):\n",
    "    U_taxa = 0.4446  # substitua esse valor se o cálculo for diferente\n",
    "    if abs(row['EPR']) > U_taxa:\n",
    "        return 'Erosão Significativa' if row['EPR'] < 0 else 'Progradação Significativa'\n",
    "    else:\n",
    "        return 'Não Significativa'\n",
    "\n",
    "df['Significância_EPR'] = df.apply(classificar_epr, axis=1)\n",
    "\n",
    "# 🔹 Função para gerar tabela de significância por setor\n",
    "def gerar_tabela_significancia_por_setor(df, coluna_significancia):\n",
    "    contagem = df.groupby(['Setor', coluna_significancia]).size().unstack(fill_value=0)\n",
    "    percentuais = contagem.div(contagem.sum(axis=1), axis=0) * 100\n",
    "    percentuais = percentuais.round(2)\n",
    "    \n",
    "    tabela_final = pd.concat(\n",
    "        [contagem, percentuais],\n",
    "        keys=['Contagem', 'Percentual'],\n",
    "        names=['Tipo']\n",
    "    )\n",
    "    return tabela_final\n",
    "\n",
    "# 🔹 Tabelas por setor\n",
    "tabela_epr = gerar_tabela_significancia_por_setor(df, 'Significância_EPR')\n",
    "tabela_lrr = gerar_tabela_significancia_por_setor(df, 'Significância_LRR')\n",
    "\n",
    "# Mostrar no Jupyter\n",
    "print(\"📊 Tabela de Incerteza por Setor - EPR\")\n",
    "display(tabela_epr)\n",
    "\n",
    "print(\"📊 Tabela de Incerteza por Setor - LRR\")\n",
    "display(tabela_lrr)\n",
    "\n",
    "# 🔹 Salvar como Excel\n",
    "caminho_epr = r'C:\\Users\\rafam\\Documents\\DSAS_ZC_ATLANTICO\\INCERTEZAS_EPR.xlsx'\n",
    "caminho_lrr = r'C:\\Users\\rafam\\Documents\\DSAS_ZC_ATLANTICO\\INCERTEZAS_LRR.xlsx'\n",
    "\n",
    "tabela_epr.to_excel(caminho_epr)\n",
    "tabela_lrr.to_excel(caminho_lrr)\n",
    "\n",
    "print(f\"\\n✔️ Arquivos salvos em:\\n{caminho_epr}\\n{caminho_lrr}\")\n",
    "\n",
    "# 🔸 Tabela Geral - EPR\n",
    "contagem_epr_geral = df['Significância_EPR'].value_counts()\n",
    "percentual_epr_geral = (contagem_epr_geral / contagem_epr_geral.sum() * 100).round(2)\n",
    "\n",
    "df_epr_geral = pd.DataFrame({\n",
    "    'Significância': contagem_epr_geral.index,\n",
    "    'Contagem': contagem_epr_geral.values,\n",
    "    'Percentual (%)': percentual_epr_geral.values\n",
    "})\n",
    "\n",
    "print(\"\\n📊 Tabela Geral - EPR\")\n",
    "display(df_epr_geral)\n",
    "\n",
    "caminho_epr_geral = r'C:\\Users\\rafam\\Documents\\DSAS_ZC_ATLANTICO\\INCERTEZAS_GERAL_EPR.xlsx'\n",
    "df_epr_geral.to_excel(caminho_epr_geral, index=False)\n",
    "print(f\"✔️ Tabela geral de EPR salva em: {caminho_epr_geral}\")\n",
    "\n",
    "# 🔹 Tabela Geral - LRR\n",
    "contagem_lrr_geral = df['Significância_LRR'].value_counts()\n",
    "percentual_lrr_geral = (contagem_lrr_geral / contagem_lrr_geral.sum() * 100).round(2)\n",
    "\n",
    "df_lrr_geral = pd.DataFrame({\n",
    "    'Significância': contagem_lrr_geral.index,\n",
    "    'Contagem': contagem_lrr_geral.values,\n",
    "    'Percentual (%)': percentual_lrr_geral.values\n",
    "})\n",
    "\n",
    "print(\"\\n📊 Tabela Geral - LRR\")\n",
    "display(df_lrr_geral)\n",
    "\n",
    "caminho_lrr_geral = r'C:\\Users\\rafam\\Documents\\DSAS_ZC_ATLANTICO\\INCERTEZAS_GERAL_LRR.xlsx'\n",
    "df_lrr_geral.to_excel(caminho_lrr_geral, index=False)\n",
    "print(f\"✔️ Tabela geral de LRR salva em: {caminho_lrr_geral}\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7072ea5b-7721-4205-b8a9-d2f752e1f0e2",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}

"code",
   "execution_count": 30,
   "id": "0765781f-ec26-4eeb-9ef5-23259deb2c8e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Incerteza da taxa calculada (U_taxa): 1.1033 m/ano\n",
      "\n",
      "✔️ Tabela de significância por setor salva em: C:\\Users\\rafam\\Documents\\DSAS_ZC_ATLANTICO\\significancia_por_setor_2024.xlsx\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "# Dados de incerteza por ano\n",
    "dados_incerteza = {\n",
    "    'Ano': [1984, 1988, 1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020, 2024],\n",
    "    'U (m)': [31.20313, 31.087496, 31.066874, 30.796462, 30.76017, 30.680610, \n",
    "              30.608914, 30.469932, 31.129918, 31.197335, 31.206661]\n",
    "}\n",
    "df_incerteza = pd.DataFrame(dados_incerteza)\n",
    "\n",
    "# Carregar dados DSAS\n",
    "caminho_arquivo = r'C:\\Users\\rafam\\Documents\\DSAS_ZC_ATLANTICO\\DSAS_GERAL.xlsx'\n",
    "df_dsas = pd.read_excel(caminho_arquivo, sheet_name='dsas')\n",
    "\n",
    "# Definir anos de início e fim\n",
    "ano_inicial = 1984\n",
    "ano_final = 2024\n",
    "U1 = df_incerteza[df_incerteza['Ano'] == ano_inicial]['U (m)'].values[0]\n",
    "U2 = df_incerteza[df_incerteza['Ano'] == ano_final]['U (m)'].values[0]\n",
    "delta_t = ano_final - ano_inicial\n",
    "\n",
    "# Cálculo atualizado de incerteza da taxa\n",
    "U_taxa = np.sqrt(U1**2 + U2**2) / delta_t\n",
    "print(f\"Incerteza da taxa calculada (U_taxa): {U_taxa:.4f} m/ano\")\n",
    "\n",
    "# Classificação com base na nova U_taxa\n",
    "def classificar_epr(epr):\n",
    "    if abs(epr) > U_taxa:\n",
    "        return 'Erosão Significativa' if epr < 0 else 'Progradação Significativa'\n",
    "    else:\n",
    "        return 'Não Significativa'\n",
    "\n",
    "# Adiciona a coluna de significância\n",
    "df_dsas['Significância'] = df_dsas['EPR'].apply(classificar_epr)\n",
    "\n",
    "# Dividir por setor\n",
    "setores = {\n",
    "    'I': 'Salinópolis', 'II': 'São João de Pirabas', 'III': 'Quatipuru',\n",
    "    'IV': 'Tracuateua', 'V': 'Bragança', 'VI': 'Augusto Corrêa', 'VII': 'Viseu'\n",
    "}\n",
    "\n",
    "# Tabela de significância por setor\n",
    "resultados_por_setor = []\n",
    "\n",
    "for setor, nome in setores.items():\n",
    "    subset = df_dsas[df_dsas['Setor'] == setor]\n",
    "    \n",
    "    # Contagem por tipo de significância\n",
    "    contagem = subset['Significância'].value_counts()\n",
    "    total_setor = len(subset)\n",
    "    percentuais = (contagem / total_setor * 100).round(2)\n",
    "    \n",
    "    # Adiciona os resultados à lista\n",
    "    resultados_por_setor.append({\n",
    "        'Setor': nome,\n",
    "        'Não Significativa (n)': contagem.get('Não Significativa', 0),\n",
    "        'Não Significativa (%)': percentuais.get('Não Significativa', 0.00),\n",
    "        'Erosão Significativa (n)': contagem.get('Erosão Significativa', 0),\n",
    "        'Erosão Significativa (%)': percentuais.get('Erosão Significativa', 0.00),\n",
    "        'Progradação Significativa (n)': contagem.get('Progradação Significativa', 0),\n",
    "        'Progradação Significativa (%)': percentuais.get('Progradação Significativa', 0.00)\n",
    "    })\n",
    "\n",
    "# Criar DataFrame de resultados por setor\n",
    "df_resultados_setor = pd.DataFrame(resultados_por_setor)\n",
    "\n",
    "# Exportar para Excel\n",
    "caminho_saida_setor = r'C:\\Users\\rafam\\Documents\\DSAS_ZC_ATLANTICO\\significancia_por_setor_2024.xlsx'\n",
    "df_resultados_setor.to_excel(caminho_saida_setor, index=False)\n",
    "\n",
    "print(f\"\\n✔️ Tabela de significância por setor salva em: {caminho_saida_setor}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 58,
   "id": "0cf665cf-6bb4-454f-adfc-770188bb81b8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "📊 Tabela de Incerteza por Setor - EPR\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Significância_EPR</th>\n",
       "      <th>Erosão Significativa</th>\n",
       "      <th>Não Significativa</th>\n",
       "      <th>Progradação Significativa</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Tipo</th>\n",
       "      <th>Setor</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th rowspan=\"7\" valign=\"top\">Contagem</th>\n",
       "      <th>I</th>\n",
       "      <td>117.00</td>\n",
       "      <td>85.00</td>\n",
       "      <td>162.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>II</th>\n",
       "      <td>257.00</td>\n",
       "      <td>62.00</td>\n",
       "      <td>334.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>III</th>\n",
       "      <td>137.00</td>\n",
       "      <td>25.00</td>\n",
       "      <td>236.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>IV</th>\n",
       "      <td>78.00</td>\n",
       "      <td>32.00</td>\n",
       "      <td>332.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>V</th>\n",
       "      <td>181.00</td>\n",
       "      <td>38.00</td>\n",
       "      <td>367.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>VI</th>\n",
       "      <td>368.00</td>\n",
       "      <td>100.00</td>\n",
       "      <td>583.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>VII</th>\n",
       "      <td>356.00</td>\n",
       "      <td>42.00</td>\n",
       "      <td>494.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th rowspan=\"7\" valign=\"top\">Percentual</th>\n",
       "      <th>I</th>\n",
       "      <td>32.14</td>\n",
       "      <td>23.35</td>\n",
       "      <td>44.51</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>II</th>\n",
       "      <td>39.36</td>\n",
       "      <td>9.49</td>\n",
       "      <td>51.15</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>III</th>\n",
       "      <td>34.42</td>\n",
       "      <td>6.28</td>\n",
       "      <td>59.30</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>IV</th>\n",
       "      <td>17.65</td>\n",
       "      <td>7.24</td>\n",
       "      <td>75.11</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>V</th>\n",
       "      <td>30.89</td>\n",
       "      <td>6.48</td>\n",
       "      <td>62.63</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>VI</th>\n",
       "      <td>35.01</td>\n",
       "      <td>9.51</td>\n",
       "      <td>55.47</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>VII</th>\n",
       "      <td>39.91</td>\n",
       "      <td>4.71</td>\n",
       "      <td>55.38</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "Significância_EPR  Erosão Significativa  Não Significativa  \\\n",
       "Tipo       Setor                                             \n",
       "Contagem   I                     117.00              85.00   \n",
       "           II                    257.00              62.00   \n",
       "           III                   137.00              25.00   \n",
       "           IV                     78.00              32.00   \n",
       "           V                     181.00              38.00   \n",
       "           VI                    368.00             100.00   \n",
       "           VII                   356.00              42.00   \n",
       "Percentual I                      32.14              23.35   \n",
       "           II                     39.36               9.49   \n",
       "           III                    34.42               6.28   \n",
       "           IV                     17.65               7.24   \n",
       "           V                      30.89               6.48   \n",
       "           VI                     35.01               9.51   \n",
       "           VII                    39.91               4.71   \n",
       "\n",
       "Significância_EPR  Progradação Significativa  \n",
       "Tipo       Setor                              \n",
       "Contagem   I                          162.00  \n",
       "           II                         334.00  \n",
       "           III                        236.00  \n",
       "           IV                         332.00  \n",
       "           V                          367.00  \n",
       "           VI                         583.00  \n",
       "           VII                        494.00  \n",
       "Percentual I                           44.51  \n",
       "           II                          51.15  \n",
       "           III                         59.30  \n",
       "           IV                          75.11  \n",
       "           V                           62.63  \n",
       "           VI                          55.47  \n",
       "           VII                         55.38  "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "📊 Tabela de Incerteza por Setor - LRR\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Significância_LRR</th>\n",
       "      <th>Erosão Significativa</th>\n",
       "      <th>Não Significativa</th>\n",
       "      <th>Progradação Significativa</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Tipo</th>\n",
       "      <th>Setor</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th rowspan=\"7\" valign=\"top\">Contagem</th>\n",
       "      <th>I</th>\n",
       "      <td>62.00</td>\n",
       "      <td>211.00</td>\n",
       "      <td>91.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>II</th>\n",
       "      <td>142.00</td>\n",
       "      <td>272.00</td>\n",
       "      <td>239.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>III</th>\n",
       "      <td>85.00</td>\n",
       "      <td>112.00</td>\n",
       "      <td>201.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>IV</th>\n",
       "      <td>68.00</td>\n",
       "      <td>91.00</td>\n",
       "      <td>283.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>V</th>\n",
       "      <td>142.00</td>\n",
       "      <td>136.00</td>\n",
       "      <td>308.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>VI</th>\n",
       "      <td>249.00</td>\n",
       "      <td>315.00</td>\n",
       "      <td>487.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>VII</th>\n",
       "      <td>261.00</td>\n",
       "      <td>207.00</td>\n",
       "      <td>424.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th rowspan=\"7\" valign=\"top\">Percentual</th>\n",
       "      <th>I</th>\n",
       "      <td>17.03</td>\n",
       "      <td>57.97</td>\n",
       "      <td>25.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>II</th>\n",
       "      <td>21.75</td>\n",
       "      <td>41.65</td>\n",
       "      <td>36.60</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>III</th>\n",
       "      <td>21.36</td>\n",
       "      <td>28.14</td>\n",
       "      <td>50.50</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>IV</th>\n",
       "      <td>15.38</td>\n",
       "      <td>20.59</td>\n",
       "      <td>64.03</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>V</th>\n",
       "      <td>24.23</td>\n",
       "      <td>23.21</td>\n",
       "      <td>52.56</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>VI</th>\n",
       "      <td>23.69</td>\n",
       "      <td>29.97</td>\n",
       "      <td>46.34</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>VII</th>\n",
       "      <td>29.26</td>\n",
       "      <td>23.21</td>\n",
       "      <td>47.53</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "Significância_LRR  Erosão Significativa  Não Significativa  \\\n",
       "Tipo       Setor                                             \n",
       "Contagem   I                      62.00             211.00   \n",
       "           II                    142.00             272.00   \n",
       "           III                    85.00             112.00   \n",
       "           IV                     68.00              91.00   \n",
       "           V                     142.00             136.00   \n",
       "           VI                    249.00             315.00   \n",
       "           VII                   261.00             207.00   \n",
       "Percentual I                      17.03              57.97   \n",
       "           II                     21.75              41.65   \n",
       "           III                    21.36              28.14   \n",
       "           IV                     15.38              20.59   \n",
       "           V                      24.23              23.21   \n",
       "           VI                     23.69              29.97   \n",
       "           VII                    29.26              23.21   \n",
       "\n",
       "Significância_LRR  Progradação Significativa  \n",
       "Tipo       Setor                              \n",
       "Contagem   I                           91.00  \n",
       "           II                         239.00  \n",
       "           III                        201.00  \n",
       "           IV                         283.00  \n",
       "           V                          308.00  \n",
       "           VI                         487.00  \n",
       "           VII                        424.00  \n",
       "Percentual I                           25.00  \n",
       "           II                          36.60  \n",
       "           III                         50.50  \n",
       "           IV                          64.03  \n",
       "           V                           52.56  \n",
       "           VI                          46.34  \n",
       "           VII                         47.53  "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "✔️ Arquivos salvos em:\n",
      "C:\\Users\\rafam\\Documents\\DSAS_ZC_ATLANTICO\\INCERTEZAS_EPR.xlsx\n",
      "C:\\Users\\rafam\\Documents\\DSAS_ZC_ATLANTICO\\INCERTEZAS_LRR.xlsx\n",
      "\n",
      "📊 Tabela Geral - EPR\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Significância</th>\n",
       "      <th>Contagem</th>\n",
       "      <th>Percentual (%)</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Progradação Significativa</td>\n",
       "      <td>2508</td>\n",
       "      <td>57.18</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Erosão Significativa</td>\n",
       "      <td>1494</td>\n",
       "      <td>34.06</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Não Significativa</td>\n",
       "      <td>384</td>\n",
       "      <td>8.76</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "               Significância  Contagem  Percentual (%)\n",
       "0  Progradação Significativa      2508           57.18\n",
       "1       Erosão Significativa      1494           34.06\n",
       "2          Não Significativa       384            8.76"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✔️ Tabela geral de EPR salva em: C:\\Users\\rafam\\Documents\\DSAS_ZC_ATLANTICO\\INCERTEZAS_GERAL_EPR.xlsx\n",
      "\n",
      "📊 Tabela Geral - LRR\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Significância</th>\n",
       "      <th>Contagem</th>\n",
       "      <th>Percentual (%)</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Progradação Significativa</td>\n",
       "      <td>2033</td>\n",
       "      <td>46.35</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Não Significativa</td>\n",
       "      <td>1344</td>\n",
       "      <td>30.64</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Erosão Significativa</td>\n",
       "      <td>1009</td>\n",
       "      <td>23.01</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "               Significância  Contagem  Percentual (%)\n",
       "0  Progradação Significativa      2033           46.35\n",
       "1          Não Significativa      1344           30.64\n",
       "2       Erosão Significativa      1009           23.01"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✔️ Tabela geral de LRR salva em: C:\\Users\\rafam\\Documents\\DSAS_ZC_ATLANTICO\\INCERTEZAS_GERAL_LRR.xlsx\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "# Carregar dados da planilha\n",
    "caminho_arquivo = r'C:\\Users\\rafam\\Documents\\DSAS_ZC_ATLANTICO\\DSAS_GERAL.xlsx'\n",
    "df = pd.read_excel(caminho_arquivo, sheet_name='dsas')\n",
    "\n",
    "# Classificação baseada em LRR e LCI90\n",
    "def classificar_lrr(row):\n",
    "    if abs(row['LRR']) > row['LCI90']:\n",
    "        return 'Erosão Significativa' if row['LRR'] < 0 else 'Progradação Significativa'\n",
    "    else:\n",
    "        return 'Não Significativa'\n",
    "\n",
    "df['Significância_LRR'] = df.apply(classificar_lrr, axis=1)\n",
    "\n",
    "# Classificação baseada em EPR e incerteza (pré-calculada)\n",
    "def classificar_epr(row):\n",
    "    U_taxa = 0.4446  # substitua esse valor se o cálculo for diferente\n",
    "    if abs(row['EPR']) > U_taxa:\n",
    "        return 'Erosão Significativa' if row['EPR'] < 0 else 'Progradação Significativa'\n",
    "    else:\n",
    "        return 'Não Significativa'\n",
    "\n",
    "df['Significância_EPR'] = df.apply(classificar_epr, axis=1)\n",
    "\n",
    "# 🔹 Função para gerar tabela de significância por setor\n",
    "def gerar_tabela_significancia_por_setor(df, coluna_significancia):\n",
    "    contagem = df.groupby(['Setor', coluna_significancia]).size().unstack(fill_value=0)\n",
    "    percentuais = contagem.div(contagem.sum(axis=1), axis=0) * 100\n",
    "    percentuais = percentuais.round(2)\n",
    "    \n",
    "    tabela_final = pd.concat(\n",
    "        [contagem, percentuais],\n",
    "        keys=['Contagem', 'Percentual'],\n",
    "        names=['Tipo']\n",
    "    )\n",
    "    return tabela_final\n",
    "\n",
    "# 🔹 Tabelas por setor\n",
    "tabela_epr = gerar_tabela_significancia_por_setor(df, 'Significância_EPR')\n",
    "tabela_lrr = gerar_tabela_significancia_por_setor(df, 'Significância_LRR')\n",
    "\n",
    "# Mostrar no Jupyter\n",
    "print(\"📊 Tabela de Incerteza por Setor - EPR\")\n",
    "display(tabela_epr)\n",
    "\n",
    "print(\"📊 Tabela de Incerteza por Setor - LRR\")\n",
    "display(tabela_lrr)\n",
    "\n",
    "# 🔹 Salvar como Excel\n",
    "caminho_epr = r'C:\\Users\\rafam\\Documents\\DSAS_ZC_ATLANTICO\\INCERTEZAS_EPR.xlsx'\n",
    "caminho_lrr = r'C:\\Users\\rafam\\Documents\\DSAS_ZC_ATLANTICO\\INCERTEZAS_LRR.xlsx'\n",
    "\n",
    "tabela_epr.to_excel(caminho_epr)\n",
    "tabela_lrr.to_excel(caminho_lrr)\n",
    "\n",
    "print(f\"\\n✔️ Arquivos salvos em:\\n{caminho_epr}\\n{caminho_lrr}\")\n",
    "\n",
    "# 🔸 Tabela Geral - EPR\n",
    "contagem_epr_geral = df['Significância_EPR'].value_counts()\n",
    "percentual_epr_geral = (contagem_epr_geral / contagem_epr_geral.sum() * 100).round(2)\n",
    "\n",
    "df_epr_geral = pd.DataFrame({\n",
    "    'Significância': contagem_epr_geral.index,\n",
    "    'Contagem': contagem_epr_geral.values,\n",
    "    'Percentual (%)': percentual_epr_geral.values\n",
    "})\n",
    "\n",
    "print(\"\\n📊 Tabela Geral - EPR\")\n",
    "display(df_epr_geral)\n",
    "\n",
    "caminho_epr_geral = r'C:\\Users\\rafam\\Documents\\DSAS_ZC_ATLANTICO\\INCERTEZAS_GERAL_EPR.xlsx'\n",
    "df_epr_geral.to_excel(caminho_epr_geral, index=False)\n",
    "print(f\"✔️ Tabela geral de EPR salva em: {caminho_epr_geral}\")\n",
    "\n",
    "# 🔹 Tabela Geral - LRR\n",
    "contagem_lrr_geral = df['Significância_LRR'].value_counts()\n",
    "percentual_lrr_geral = (contagem_lrr_geral / contagem_lrr_geral.sum() * 100).round(2)\n",
    "\n",
    "df_lrr_geral = pd.DataFrame({\n",
    "    'Significância': contagem_lrr_geral.index,\n",
    "    'Contagem': contagem_lrr_geral.values,\n",
    "    'Percentual (%)': percentual_lrr_geral.values\n",
    "})\n",
    "\n",
    "print(\"\\n📊 Tabela Geral - LRR\")\n",
    "display(df_lrr_geral)\n",
    "\n",
    "caminho_lrr_geral = r'C:\\Users\\rafam\\Documents\\DSAS_ZC_ATLANTICO\\INCERTEZAS_GERAL_LRR.xlsx'\n",
    "df_lrr_geral.to_excel(caminho_lrr_geral, index=False)\n",
    "print(f\"✔️ Tabela geral de LRR salva em: {caminho_lrr_geral}\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7072ea5b-7721-4205-b8a9-d2f752e1f0e2",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}