{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "506b163a-ac29-4117-8520-df8de2479d14",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "===== TABELA NSM =====\n",
      "                 Setor  NSM médio (m)  Erosão líquida (%)  Erosão máxima (m)  \\\n",
      "0          Salinópolis           2.32               34.07           -1076.31   \n",
      "1  São João de Pirabas          21.03               39.97           -1688.31   \n",
      "2            Quatipuru          77.89               34.42           -1108.83   \n",
      "3           Tracuateua         290.05               19.00           -1112.16   \n",
      "4             Bragança         102.24               31.06           -1714.54   \n",
      "5       Augusto Corrêa          50.45               35.68            -889.96   \n",
      "6                Viseu          44.98               40.13           -1295.21   \n",
      "\n",
      "   ID erosão máxima  Acréscimo líquida (%)  Acréscimo máxima (m)  \\\n",
      "0               361                  46.43               1079.78   \n",
      "1               571                  52.07               1521.98   \n",
      "2              1390                  59.30               1086.91   \n",
      "3              1751                  75.57               1504.55   \n",
      "4              2296                  63.48               1184.94   \n",
      "5              3085                  56.04               1836.95   \n",
      "6              3661                  56.17               1639.80   \n",
      "\n",
      "   ID acréscimo máxima  \n",
      "0                  362  \n",
      "1                  373  \n",
      "2                 1290  \n",
      "3                 1813  \n",
      "4                 2434  \n",
      "5                 3320  \n",
      "6                 4276  \n",
      "\n",
      "===== TABELA EPR =====\n",
      "                 Setor Taxa Média (m/ano) Taxa Média de Erosão (m/ano)  \\\n",
      "0          Salinópolis         0.10 ± 1.1                 -26.91 ± 1.1   \n",
      "1  São João de Pirabas         0.05 ± 1.1                 -84.42 ± 1.1   \n",
      "2            Quatipuru         1.95 ± 1.1                 -29.17 ± 1.1   \n",
      "3           Tracuateua         7.71 ± 1.1                  -27.8 ± 1.1   \n",
      "4             Bragança         3.06 ± 1.1                 -42.86 ± 1.1   \n",
      "5       Augusto Corrêa         1.16 ± 1.1                 -36.12 ± 1.1   \n",
      "6                Viseu         1.07 ± 1.1                 -71.47 ± 1.1   \n",
      "\n",
      "   ID Erosão Máxima Porcentagem de Erosão (%) Erosão Máxima (m/ano)  \\\n",
      "0               361                    34.07%          -26.91 ± 1.1   \n",
      "1               571                    39.97%          -84.42 ± 1.1   \n",
      "2              1260                    34.42%          -29.17 ± 1.1   \n",
      "3              1751                     19.0%           -27.8 ± 1.1   \n",
      "4              2296                    31.06%          -42.86 ± 1.1   \n",
      "5              3235                    35.68%          -36.12 ± 1.1   \n",
      "6              4027                    40.13%          -71.47 ± 1.1   \n",
      "\n",
      "   ID Acréscimo Máxima Taxa Média de Acréscimo (m/ano)  \\\n",
      "0                  362                    +26.99 ± 1.1   \n",
      "1                  371                    +74.71 ± 1.1   \n",
      "2                 1290                    +27.17 ± 1.1   \n",
      "3                 1813                    +37.61 ± 1.1   \n",
      "4                 2328                    +69.91 ± 1.1   \n",
      "5                 3320                    +45.92 ± 1.1   \n",
      "6                 4277                    +57.56 ± 1.1   \n",
      "\n",
      "  Porcentagem de Acréscimo (%) Acréscimo Máximo (m/ano)  \n",
      "0                       46.43%             +26.99 ± 1.1  \n",
      "1                       52.07%             +74.71 ± 1.1  \n",
      "2                        59.3%             +27.17 ± 1.1  \n",
      "3                       75.57%             +37.61 ± 1.1  \n",
      "4                       63.48%             +69.91 ± 1.1  \n",
      "5                       56.04%             +45.92 ± 1.1  \n",
      "6                       56.17%             +57.56 ± 1.1  \n",
      "\n",
      "===== TABELA LRR =====\n",
      "                 Setor Taxa Média (m/ano) Taxa Média de Erosão (m/ano)  \\\n",
      "0          Salinópolis              -0.05                -30.63 ± 0.54   \n",
      "1  São João de Pirabas               0.78                -83.66 ± 0.36   \n",
      "2            Quatipuru               1.93                -24.95 ± 0.89   \n",
      "3           Tracuateua               7.39                -28.82 ± 0.83   \n",
      "4             Bragança               2.74                -62.08 ± 0.55   \n",
      "5       Augusto Corrêa               0.67                -29.75 ± 0.74   \n",
      "6                Viseu               1.06                 -71.47 ± 0.8   \n",
      "\n",
      "   ID Erosão Máxima Porcentagem de Erosão (%) Erosão Máxima (m/ano)  \\\n",
      "0               139                    43.96%         -30.63 ± 0.54   \n",
      "1               570                    39.66%         -83.66 ± 0.36   \n",
      "2              1260                     39.2%         -24.95 ± 0.89   \n",
      "3              1751                    24.66%         -28.82 ± 0.83   \n",
      "4              2296                    34.13%         -62.08 ± 0.55   \n",
      "5              3084                    38.06%         -29.75 ± 0.74   \n",
      "6              4027                    42.04%          -71.47 ± 0.8   \n",
      "\n",
      "   ID Acréscimo Máxima Taxa Média de Acréscimo (m/ano)  \\\n",
      "0                  163                    +21.41 ± 1.2   \n",
      "1                  371                     +88.4 ± 1.4   \n",
      "2                 1302                    +27.95 ± 1.7   \n",
      "3                 1827                    +39.23 ± 1.2   \n",
      "4                 2379                    +40.62 ± 1.2   \n",
      "5                 2628                    +33.56 ± 2.4   \n",
      "6                 4275                    +55.47 ± 2.6   \n",
      "\n",
      "  Porcentagem de Acréscimo (%) Acréscimo Máximo (m/ano)  \n",
      "0                       50.82%             +21.41 ± 1.2  \n",
      "1                       58.65%              +88.4 ± 1.4  \n",
      "2                       58.54%             +27.95 ± 1.7  \n",
      "3                       73.98%             +39.23 ± 1.2  \n",
      "4                       63.14%             +40.62 ± 1.2  \n",
      "5                       57.85%             +33.56 ± 2.4  \n",
      "6                       57.06%             +55.47 ± 2.6  \n",
      "\n",
      "===== TABELA LR2 (R²) =====\n",
      "                 Setor  Total de Transectos  R² > 0,5 (n)  R² ≤ 0,5 (n)  \\\n",
      "0          Salinópolis                  364           115           249   \n",
      "1  São João de Pirabas                  653           293           360   \n",
      "2            Quatipuru                  398           235           163   \n",
      "3           Tracuateua                  442           314           128   \n",
      "4             Bragança                  586           379           207   \n",
      "5       Augusto Corrêa                 1051           619           432   \n",
      "6                Viseu                  892           551           341   \n",
      "\n",
      "  R² > 0,5 (%) R² ≤ 0,5 (%)  \n",
      "0       31.59%       68.41%  \n",
      "1       44.87%       55.13%  \n",
      "2       59.05%       40.95%  \n",
      "3       71.04%       28.96%  \n",
      "4       64.68%       35.32%  \n",
      "5       58.90%       41.10%  \n",
      "6       61.77%       38.23%  \n",
      "\n",
      "✔️ Tabelas exportadas com sucesso para: C:\\Users\\rafam\\Documents\\DSAS_ZC_ATLANTICO\\tabelas_resultados.xlsx\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "\n",
    "# Caminho do arquivo Excel\n",
    "caminho = r\"C:\\Users\\rafam\\Documents\\DSAS_ZC_ATLANTICO\\DSAS_GERAL.xlsx\"\n",
    "df = pd.read_excel(caminho)\n",
    "\n",
    "# ---------- 1. TABELA NSM ----------\n",
    "def tabela_nsm(df):\n",
    "    setores = {\n",
    "        'I': 'Salinópolis', 'II': 'São João de Pirabas', 'III': 'Quatipuru',\n",
    "        'IV': 'Tracuateua', 'V': 'Bragança', 'VI': 'Augusto Corrêa', 'VII': 'Viseu'\n",
    "    }\n",
    "    resultados = []\n",
    "    for setor, nome in setores.items():\n",
    "        subset = df[df['Setor'] == setor]\n",
    "        erosao = subset[subset['NSM'] < 0]\n",
    "        acrescimo = subset[subset['NSM'] > 0]\n",
    "        total = len(subset)\n",
    "\n",
    "        id_erosao_max = subset.loc[erosao['NSM'].idxmin(), 'ID_atualiz'] if not erosao.empty else None\n",
    "        nsm_erosao_max = round(erosao['NSM'].min(), 2) if not erosao.empty else None\n",
    "        id_acrescimo_max = subset.loc[acrescimo['NSM'].idxmax(), 'ID_atualiz'] if not acrescimo.empty else None\n",
    "        nsm_acrescimo_max = round(acrescimo['NSM'].max(), 2) if not acrescimo.empty else None\n",
    "\n",
    "        resultados.append({\n",
    "            'Setor': nome,\n",
    "            'NSM médio (m)': round(subset['NSM'].mean(), 2) if not subset.empty else None,\n",
    "            'Erosão líquida (%)': round(len(erosao) / total * 100, 2) if total else 0,\n",
    "            'Erosão máxima (m)': nsm_erosao_max,\n",
    "            'ID erosão máxima': id_erosao_max,\n",
    "            'Acréscimo líquida (%)': round(len(acrescimo) / total * 100, 2) if total else 0,\n",
    "            'Acréscimo máxima (m)': nsm_acrescimo_max,\n",
    "            'ID acréscimo máxima': id_acrescimo_max\n",
    "        })\n",
    "    return pd.DataFrame(resultados)\n",
    "\n",
    "# ---------- 2. TABELA EPR ----------\n",
    "def tabela_epr(df):\n",
    "    setores = {\n",
    "        'I': 'Salinópolis', 'II': 'São João de Pirabas', 'III': 'Quatipuru',\n",
    "        'IV': 'Tracuateua', 'V': 'Bragança', 'VI': 'Augusto Corrêa', 'VII': 'Viseu'\n",
    "    }\n",
    "    erro_associado = 1.10\n",
    "    resultados = []\n",
    "    for setor, nome in setores.items():\n",
    "        subset = df[df['Setor'] == setor]\n",
    "        total = len(subset)\n",
    "        if total == 0:\n",
    "            continue\n",
    "        erosao = subset[subset['EPR'] < 0]\n",
    "        acrescimo = subset[subset['EPR'] > 0]\n",
    "        \n",
    "        id_erosao_max = subset.loc[erosao['EPR'].idxmin(), 'ID_atualiz'] if not erosao.empty else None\n",
    "        epr_erosao_max = round(erosao['EPR'].min(), 2) if not erosao.empty else None\n",
    "        id_acrescimo_max = subset.loc[acrescimo['EPR'].idxmax(), 'ID_atualiz'] if not acrescimo.empty else None\n",
    "        epr_acrescimo_max = round(acrescimo['EPR'].max(), 2) if not acrescimo.empty else None\n",
    "\n",
    "        resultados.append({\n",
    "            'Setor': nome,\n",
    "            'Taxa Média (m/ano)': f\"{subset['EPR'].mean():.2f} ± {erro_associado}\",\n",
    "            'Taxa Média de Erosão (m/ano)': f\"{epr_erosao_max} ± {erro_associado}\" if epr_erosao_max is not None else \"-\",\n",
    "            'ID Erosão Máxima': id_erosao_max,\n",
    "            'Porcentagem de Erosão (%)': f\"{round(len(erosao) / total * 100, 2)}%\",\n",
    "            'Erosão Máxima (m/ano)': f\"{epr_erosao_max} ± {erro_associado}\" if epr_erosao_max is not None else \"-\",\n",
    "            'ID Acréscimo Máxima': id_acrescimo_max,\n",
    "            'Taxa Média de Acréscimo (m/ano)': f\"+{epr_acrescimo_max} ± {erro_associado}\" if epr_acrescimo_max is not None else \"-\",\n",
    "            'Porcentagem de Acréscimo (%)': f\"{round(len(acrescimo) / total * 100, 2)}%\",\n",
    "            'Acréscimo Máximo (m/ano)': f\"+{epr_acrescimo_max} ± {erro_associado}\" if epr_acrescimo_max is not None else \"-\"\n",
    "        })\n",
    "    return pd.DataFrame(resultados)\n",
    "\n",
    "# ---------- 3. TABELA LRR ----------\n",
    "def tabela_lrr(df):\n",
    "    setores = {\n",
    "        'I': 'Salinópolis', 'II': 'São João de Pirabas', 'III': 'Quatipuru',\n",
    "        'IV': 'Tracuateua', 'V': 'Bragança', 'VI': 'Augusto Corrêa', 'VII': 'Viseu'\n",
    "    }\n",
    "    erros_setores = {\n",
    "        'I': {'erosao': 0.54, 'acrecao': 1.2}, 'II': {'erosao': 0.36, 'acrecao': 1.4},\n",
    "        'III': {'erosao': 0.89, 'acrecao': 1.7}, 'IV': {'erosao': 0.83, 'acrecao': 1.2},\n",
    "        'V': {'erosao': 0.55, 'acrecao': 1.2}, 'VI': {'erosao': 0.74, 'acrecao': 2.4},\n",
    "        'VII': {'erosao': 0.80, 'acrecao': 2.6},\n",
    "    }\n",
    "    resultados = []\n",
    "    for setor, nome in setores.items():\n",
    "        subset = df[df['Setor'] == setor]\n",
    "        total = len(subset)\n",
    "        if total == 0:\n",
    "            continue\n",
    "        erosao = subset[subset['LRR'] < 0]\n",
    "        acrescimo = subset[subset['LRR'] > 0]\n",
    "        erro_erosao = erros_setores[setor]['erosao']\n",
    "        erro_acrecao = erros_setores[setor]['acrecao']\n",
    "\n",
    "        id_erosao_max = subset.loc[erosao['LRR'].idxmin(), 'ID_atualiz'] if not erosao.empty else None\n",
    "        lrr_erosao_max = round(erosao['LRR'].min(), 2) if not erosao.empty else None\n",
    "        id_acrescimo_max = subset.loc[acrescimo['LRR'].idxmax(), 'ID_atualiz'] if not acrescimo.empty else None\n",
    "        lrr_acrescimo_max = round(acrescimo['LRR'].max(), 2) if not acrescimo.empty else None\n",
    "\n",
    "        resultados.append({\n",
    "            'Setor': nome,\n",
    "            'Taxa Média (m/ano)': f\"{subset['LRR'].mean():.2f}\",\n",
    "            'Taxa Média de Erosão (m/ano)': f\"{lrr_erosao_max} ± {erro_erosao}\" if lrr_erosao_max is not None else \"-\",\n",
    "            'ID Erosão Máxima': id_erosao_max,\n",
    "            'Porcentagem de Erosão (%)': f\"{round(len(erosao) / total * 100, 2)}%\",\n",
    "            'Erosão Máxima (m/ano)': f\"{lrr_erosao_max} ± {erro_erosao}\" if lrr_erosao_max is not None else \"-\",\n",
    "            'ID Acréscimo Máxima': id_acrescimo_max,\n",
    "            'Taxa Média de Acréscimo (m/ano)': f\"+{lrr_acrescimo_max} ± {erro_acrecao}\" if lrr_acrescimo_max is not None else \"-\",\n",
    "            'Porcentagem de Acréscimo (%)': f\"{round(len(acrescimo) / total * 100, 2)}%\",\n",
    "            'Acréscimo Máximo (m/ano)': f\"+{lrr_acrescimo_max} ± {erro_acrecao}\" if lrr_acrescimo_max is not None else \"-\"\n",
    "        })\n",
    "    return pd.DataFrame(resultados)\n",
    "\n",
    "# ---------- 4. TABELA LR2 (R²) ----------\n",
    "def tabela_lr2(df):\n",
    "    setores = {\n",
    "        'I': 'Salinópolis', 'II': 'São João de Pirabas', 'III': 'Quatipuru',\n",
    "        'IV': 'Tracuateua', 'V': 'Bragança', 'VI': 'Augusto Corrêa', 'VII': 'Viseu'\n",
    "    }\n",
    "    resultados = []\n",
    "    for setor, nome in setores.items():\n",
    "        subset = df[df['Setor'] == setor]\n",
    "        total = len(subset)\n",
    "        if total == 0:\n",
    "            continue\n",
    "        r2_maior = subset[subset['LR2'] > 0.5]\n",
    "        r2_menor = subset[subset['LR2'] <= 0.5]\n",
    "\n",
    "        resultados.append({\n",
    "            'Setor': nome,\n",
    "            'Total de Transectos': total,\n",
    "            'R² > 0,5 (n)': len(r2_maior),\n",
    "            'R² ≤ 0,5 (n)': len(r2_menor),\n",
    "            'R² > 0,5 (%)': f\"{(len(r2_maior)/total)*100:.2f}%\",\n",
    "            'R² ≤ 0,5 (%)': f\"{(len(r2_menor)/total)*100:.2f}%\"\n",
    "        })\n",
    "    return pd.DataFrame(resultados)\n",
    "\n",
    "# Gerar tabelas\n",
    "tabela_nsm_final = tabela_nsm(df)\n",
    "tabela_epr_final = tabela_epr(df)\n",
    "tabela_lrr_final = tabela_lrr(df)\n",
    "tabela_lr2_final = tabela_lr2(df)\n",
    "\n",
    "# Visualização\n",
    "print(\"\\n===== TABELA NSM =====\")\n",
    "print(tabela_nsm_final)\n",
    "print(\"\\n===== TABELA EPR =====\")\n",
    "print(tabela_epr_final)\n",
    "print(\"\\n===== TABELA LRR =====\")\n",
    "print(tabela_lrr_final)\n",
    "print(\"\\n===== TABELA LR2 (R²) =====\")\n",
    "print(tabela_lr2_final)\n",
    "\n",
    "# Exportar para Excel\n",
    "caminho_saida = r\"C:\\Users\\rafam\\Documents\\DSAS_ZC_ATLANTICO\\tabelas_resultados.xlsx\"\n",
    "\n",
    "with pd.ExcelWriter(caminho_saida, engine='openpyxl', mode='w') as writer:\n",
    "    tabela_nsm_final.to_excel(writer, sheet_name='NSM', index=False)\n",
    "    tabela_epr_final.to_excel(writer, sheet_name='EPR', index=False)\n",
    "    tabela_lrr_final.to_excel(writer, sheet_name='LRR', index=False)\n",
    "    tabela_lr2_final.to_excel(writer, sheet_name='LR2', index=False)\n",
    "\n",
    "print(\"\\n✔️ Tabelas exportadas com sucesso para:\", caminho_saida)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c1b802c6-b2d4-483a-8497-9a5171b3b497",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9528469f-97a8-43af-b2fc-9b0388bb10f6",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}